version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: task_management_db
    volumes:
      - db_data:/var/lib/mysql
      - ./task_management_db.sql:/docker-entrypoint-initdb.d/task_management_db.sql
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - app-network

  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
